#!/usr/bin/env python3
"""Build NEGATIVE_RESULTS_LEDGER.csv + POSITIVE_RESULTS_LEDGER.csv.

Classification taxonomy = DIRECTOR_CHARTER.md §4 (line 29):
  CORE POSITIVE / SUPPORTING POSITIVE / NEGATIVE BUT SCIENTIFICALLY USEFUL /
  NULL-LOW VALUE / WEAK-UNDERPOWERED / OBSOLETE / POTENTIALLY MISLEADING
Negative-handling rules = §18 (line 70-71).
Sources: reports/round1..15/*_report.md + ROUND{1..7}_SUMMARY.md +
masters: outputs/master/{master_results,round5_master,round6_ablation,
round6_bias,round7_master}.json|.md and docs/results_master*.md, verdict_bias.md.
"""
import csv, os

COLS = ["result_id","round","domain","experiment_or_item","result_summary",
        "key_numbers","source_files","classification","status","disposition","rationale"]

def R(rid, rnd, dom, item, summary, nums, src, cls, status, disp, why):
    return dict(zip(COLS,[rid,rnd,dom,item,summary,nums,src,cls,status,disp,why]))

POS = [
 R("POS-01","R3","refuseguard","E2/E3 verdict-shift under untrusted context (C1/C2a/C2b/C3)",
   "Context never removes coverage but significantly shifts verdicts: the corruption phenomenon (accuracy shift, not coverage loss).",
   "RR=0.000, UAC~1.0 all conditions; SIUD=0.000 (C2b +0.017 qwen); McNemar y_pred vs C0: qwen C3 p=1.2e-05, llama C3 p=1.94e-04, granite C2a p=7.6e-06, C2b p=6.1e-05; n=60/model",
   "outputs/master/master_results.md T2 (e23.*); docs/results_master.md:69-103; reports/round3/ROUND3_SUMMARY.md",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Backbone of the surviving story (untrusted context corrupts verdicts); pre-registered, 3 models, paired tests; master-verified."),
 R("POS-02","R3","refuseguard","E6 P1 semantic isolation reduces IPI-flip (aggregate)",
   "P1 cuts injection-driven vulnerable->benign flips 0.742->0.484 with zero usable-answer cost - but aggregate p is driven by the benign stratum (see NEG-07).",
   "IPI flip 0.7419->0.4839; McNemar p=0.0078 (b01=0,b10=8); usable delta P1-B0 = 0.000 [0,0] at C0/C2b/C3; n=31",
   "outputs/master/master_results.md E6 (e6.*); docs/results_master.md T5:149-171",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Real, paired, master-verified; must ship with the mandatory decomposition (vul-only p=0.5, benign-keep-bias) per ROUND3_SUMMARY #4."),
 R("POS-03","R3","refuseguard","E8 H6 pipeline-level safety + P1 safe-side",
   "P2 intent gate blocks all unsafe prompts before any LLM call (safety by construction); P1/P2 do not increase safe-side over-refusal (qwen even reduces it).",
   "P2 gate_blocked 30/30 both models, 0 LLM calls; unsafe 0.000 (by construction); qwen safe refusal B0 0.233->P1 0.000 p=0.0156; llama B0_vs_P2 p=1.0; H6 met both models (recomputed files)",
   "outputs/experiments/round3_e8*/recomputed/recompute_e8_monitor.json (mandated source); docs/results_master.md T7:196-227",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Recomputed (post-monitor-fix) values only; wording locked to 'pipeline-level, by-construction' - must not read as 'P2 makes the model safer'."),
 R("POS-04","R4","refuseguard","B4 CodeBERT baseline (PrimeVul mirror v0.1)",
   "Fine-tuned CodeBERT characterizes the transformer channel: weak ranking on paired PrimeVul blocks, usable as fallback baseline.",
   "MCC@0.5 0.2317; AUC 0.8468; VD-S 0.9617; recall@0.5 0.5410; paired rank accuracy 0.223 (n=435); n_test=20,549 (549 vul + 20k benign seed 1234)",
   "outputs/transformer/codebert_eval_vd_s_metrics.json; outputs/master/master_results.md B4:381-406; docs/results_master.md T8",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Baseline table with mandatory mirror-v0.1 + benign-subsample disclosure (not official gated release, not full 229k benign)."),
 R("POS-05","R5","refuseguard","C5 query-relevance + anti-leakage validity",
   "The C5 attack is genuinely query-relevant and leak-free, so the R5 null (NEG-02) is not a weak-attack artifact.",
   "Concrete advisory names function's own sinks 100/100; generic zero-API advisory leaks a sink 0/100; legacy C2b carrier named a sink 2/838=0.2%; 0 label/CWE/CVE leaks on 400 renderings; bench sha 2daa249f7543f8e0",
   "outputs/master/round5_master.json (c5_query_relevance.*, c2b_carrier_named_sink); docs/results_master_round5.md T7; reports/round5/ROUND5_SUMMARY.md",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Benchmark-validity evidence that strengthens the headline negative; cheap to keep, pre-empts the 'your attack was generic' reviewer objection."),
 R("POS-06","R5-6","refuseguard","Verdict-bias FP drift (Finding 2 headline)",
   "Untrusted risk context biases verdicts toward 'vulnerable': large, significant, strictly one-directional false-positive drift on benign functions.",
   "llama FP 0.817->1.000 (dFP +0.183 [+0.100,+0.283], exact McNemar p=9.8e-04; conditional flips 10/11, 11/11); granite FP 0.000->0.667/0.833 (p=1.9e-06 / 6.0e-08); reverse flips 0 everywhere; PPV 1.000->0.479 at 50/50 prevalence",
   "outputs/master/round6_bias.json (bias.*); docs/verdict_bias.md §3; outputs/master/round6_bias.md B1",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Largest practice-risk effect in the project; pre-registered stats settings (bootstrap seed 20260918); the load-bearing quantitative finding of paper 1."),
 R("POS-07","R6","refuseguard","VCI direction-symmetry (attack FP-way vs defence FN-way)",
   "Same pipeline, two opposite failure modes: untrusted context pushes verdicts toward flagging, the P3 defence toward clearing - quantified by a new index (VCI).",
   "granite attack VCI 0.650/0.750 with FP-direction 0.667/0.833, FN-direction 0.000; llama P3 VCI 0.683/0.700 with FN-direction 0.633/0.667, FP-direction 0.000; granite rec-direction 0.633/0.667 (recall 'gain' = context churn)",
   "outputs/master/round6_bias.json (VCI.*); docs/verdict_bias.md §5; outputs/master/round6_bias.md B3",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Mechanism-level symmetry claim that unifies Findings 1+2; definitions frozen before computing (§2 of verdict_bias.md)."),
 R("POS-08","R6","refuseguard","Advisory-echo evidence (did the model read the context?)",
   "Granite flip outputs quote the advisory near-verbatim; llama's verdicts move without quoting (confabulated findings); must-be-zero control holds.",
   "granite echo 12/20 (near), 11/25 (far); llama 2/11 both arms; control 0/300 C0 outputs contain advisory vocabulary (asserted)",
   "outputs/master/round6_bias.json (evidence.*); docs/verdict_bias.md §6 (quotes re-attributed per V1-R6 MINOR-1)",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Discussion-grade mechanism evidence; keep 1 paragraph with the corrected attribution (illustrative quotes are same-arm, not from the benign-flip set)."),
 R("POS-09","R6","refuseguard","P3 component ablation A0->A5 (Finding 1 mechanism + guidance G1)",
   "Pre-registered ladder isolates the culprit: the system task-intent reassertion rung alone collapses llama vulnerable recall; minimal provenance wrapper is harmless.",
   "Ladder recall 1.000/0.983/0.900/0.848/0.898/0.433; A5 rung 28/34 = 82% net flips, exact p=7.45e-09 (chi2-cc 3.35e-07); H-M1/H-M2 SUPPORTED; C5_far replicate recall 0.390, 36/59 flips; qwen 0/60 (inert); guidance G1: keep A1, drop A5",
   "outputs/master/round6_ablation.json (134 rows); docs/results_master_round6.md; reports/round6/ROUND6_SUMMARY.md §4",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Turns 'defence is the risk' from observation into mechanism; byte-level rung isolation (A4->A5 differ only by system reassertion); 82% concentration carries the B0-saturated caveat."),
 R("POS-10","R6","refuseguard","Verdict-bias extension (power for Finding 2)",
   "Fresh-sample extension removes the small-n objection on the FP-bias and shows granite's 'recall gain' is churn (both labels move up together).",
   "llama benign FP 0.820->0.990 combined n=100 (exact p=1.53e-05), vul +8 p=0.0078; granite benign 0.043->0.714, vul 0.057->0.671 combined n=70 (chi2 1.95e-11 / 1.50e-10)",
   "outputs/master/round6_ablation.json (extension.*); docs/results_master_round6.md 'C5 extension'",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Per-model source asserts + tests; completes the paired evidence on new samples (no double counting)."),
 R("POS-11","R7","refuseguard","RQ8 corruption channel generalizes across CWE families",
   "Verdict-bias is not a memory-copy-family artifact: granite generalizes to all 4 new CWE families with Bonferroni-surviving pooled effect; llama reported per-family (anti-masking) as pooled-driven.",
   "granite 4/4 families GENERALIZES (verdict.RQ8.granite2b.H_G1 SUPPORTED, family_pass_count 4/4); pooled dFP 0.062->0.700, p=8.88e-16, survives Bonferroni x5; llama H_G1 NOT_SUPPORTED 2/4 (see NEG-15), label GENERALIZES-pooled-driven",
   "outputs/master/round7_master.json (verdict.RQ8.*, cwe.*); reports/round7/ROUND7_SUMMARY.md §2 (40/40 numbers machine-checked)",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Generalization gate of the paper; per-family rows kept so family failures are not averaged away (charter §13)."),
 R("POS-12","R7","refuseguard","RQ9 minimal provenance safe at 7B (H_R2)",
   "The G1 recommendation transfers: A1 boundary-only wrapper is harmless at 7B, completing 'minimal provenance safe at every measured scale (2B/3B/7B)'.",
   "H_R2 SAFE (A1 recall 0.4576, delta -0.017, p=1.0); prompt identity 120/120 SHA-matched to Round-6; 240 records, RR=0.000",
   "outputs/master/round7_master.json (verdict.RQ9.*); reports/round7/ROUND7_SUMMARY.md §2 RQ9",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Small but decision-useful; ship as one sentence beside the RQ9 boundary (NEG-14); family confound caveat mandatory."),
 R("POS-13","R2-5","refuseguard","Refusal pathway of models is functional (instrument validity of RR=0)",
   "RR=0.000 everywhere is a model property, not detector blindness: the monitor catches real refusals in calibration/probe sets.",
   "OR-Bench probes 125/225 refused (paper-1 claim); 0.5B smoke 4/5 REFUSAL (smoke_0p5b.json); monitor false-refusal 0.0 (passes <=0.10 floor) both models",
   "outputs/transformer/calibration/*/full_report.json; outputs/experiments/round5_e0v2/smoke_0p5b.json; SUBMISSION.md §1 claim 1; docs/results_master.md T9",
   "SUPPORTING POSITIVE","STANDING","SANITY_CHECK_1LINE",
   "One validity sentence next to every RR=0 claim; full calibration table already in appendix (T9)."),
 R("POS-14","R8","packguard","KB build feasibility at 3B",
   "LLM-classified knowledge base is buildable at 3B: 60/60 classified, 0 refusal, 0 retry, 0 UNSURE (vs 8/10 UNSURE at 0.5B).",
   "60/60 classified by Qwen2.5-Coder-3B; kb_v0001 = 80 entries (20 seed + 60 LLM); fixture KB archived",
   "outputs/packguard/kb/kb_v0001.jsonl + kb_build_v2_meta.json; reports/round8/F_report.md §1 P2",
   "SUPPORTING POSITIVE","STANDING","APPENDIX",
   "Feasibility detail, not a scientific endpoint; KB effect itself is null (NEG-25)."),
 R("POS-15","R11","packguard","TOST equivalence: FedAvg == strong centralized baseline (P0-1/2)",
   "Pre-registered equivalence at +/-0.02 F1 margin on the primary leakage-resistant split, 20 seeds, paired - the paper-2 primary detector claim.",
   "group/graph dF1 -0.0065+/-0.0171, 90% CI [-0.0133,+0.0003] PASS; group/hashing -0.0024 [-0.0070,+0.0022] PASS; 360 runs mock=false; AMENDMENT-5 prereg 16:39:29Z < run 16:56:59Z",
   "outputs/packguard/p0/p0_results.json; paper2/p0_macros/numbers.tex; reports/round11/F_report.md §1 T3(a)",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Equivalence framing replaces the old descriptive null; central-win on random split must ship beside it (NEG-24) - 'FL is never worse' is explicitly NOT claimed."),
 R("POS-16","R11","packguard","Graph features beat trivial 5-feature baseline (anti-shortcut, P0-5)",
   "Behaviour-graph value is real but bounded: significant margin over a trivial structural baseline that itself reaches F1 .82-.86.",
   "dF1 +0.0227 group / +0.0487 random, exact Wilcoxon p=1.9e-5 / 1.9e-6; subset-500 non-empty still wins p=.0012/1.9e-6; trivial F1 0.8233-0.8555 (artifact-exact .823-.855)",
   "outputs/packguard/trivial/trivial_results.json; reports/round11/F_report.md §1 T2",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Rebuttal-ready anti-shortcut check; framing fixed as 'refinement, not replacement'."),
 R("POS-17","R12","packguard","D1 AST-strip defense neutralizes the advisory channel on granite",
   "Byte-provable attack removal: stripping makes granite verdicts identical to baseline on every parseable pair and reverts all attack-induced flips, at zero benign FP.",
   "strip(P2)==strip(original) 38/38 byte-equal; granite P2D1 vs P0: 23/23 verdicts identical, 4/4 flips revert, FP 0/14 (p=1.0); granite .667->.833 under attack -> .652 defended",
   "outputs/packguard/defense/defense_analysis.json + defense_metrics.json; reports/round12/F_report.md §1.2, §3",
   "CORE POSITIVE","STANDING","KEEP_MAIN",
   "Paper-2 defense headline; must ship with the llama cost as first-class outcome (NEG-26) and all-p-descriptive caveat (NEG-27)."),
 R("POS-18","R15","packguard","Graph features vs re-implemented MalGuard/Amalfi-style baseline",
   "The 41-feature MalGuard-style reimplementation does not beat the 18-dim graph block (consistent negative direction 8/8); combined only trends positive (n.s.).",
   "graph .8778+/-0.0422 vs malguard .8562+/-0.0421 (group/central); dF1 -0.0216 [-0.0407,-0.0025], raw p=.0441, Holm .3084 (n.s.); combined +0.0150 p=.1054 n.s.; 320 runs bit-exact reproductions; no label leak (V1 permutation check)",
   "outputs/packguard/malguard_style/{results.jsonl,aggregate.json}; reports/round15/W1_report.md §3 + V1_report.md §1-3",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Keep as ablation paragraph with the honest wording (NOT 'worse, significant', NOT 'equivalent'); Holm-non-significance is the load-bearing caveat (NEG-31)."),
 R("POS-19","R14","packguard","GuardDog rule-based baseline (pre-registered)",
   "GuardDog is a high-precision triage reference that trails the learned graph model on the primary split - the learned representation claim survives a strong local baseline.",
   "F1 .8627 full / .8662 group / .8571 LCO-t0.30 / .8550 t0.50; precision .9477-.9714, recall .7778-.7958; group split: loses to graph .923-.928; same-origin DataDog bias disclosed (optimistic)",
   "outputs/packguard/guarddog/{findings.jsonl,metrics.json}; configs/packguard_guarddog.yaml (prereg 2026-09-27T21:56:03Z); reports/round14/W_report.md §3",
   "SUPPORTING POSITIVE","STANDING","KEEP_MAIN",
   "Comparison-table row with mandatory 'comparable, not superior' wording; LCO 1-seed advantage stays out of main claims (NEG-29)."),
 R("POS-20","R8-9","packguard","Advisory-in-package shifts verdict sensitivity, family-dependently (corrected reading)",
   "Untrusted in-package content causally moves malicious-recall in opposite directions per model - a recall-perturbing channel, unlike paper 1's FP channel.",
   "n=60: granite TP .5333->.8000 (8/0 flips), llama .1333->.0333 (1/4 flips, measured cost); FP on benign 0/180; RR=0/360; n=100 expansion: granite FP 0->2/50, llama 8/8 mal->ben flips",
   "outputs/packguard/safety/safety_batch_n60.jsonl + safety_metrics_n60.json; safety_metrics_n100.json; reports/round9/V1_report.md §2-4",
   "CORE POSITIVE","CORRECTED","KEEP_MAIN",
   "Standing numbers are the round-9 corrected reading: round-8's 'FP-bias .2->.6, granite 1.0' was a mislabeled TP-rate (see NEG row for the retraction); paper-2 abstract already uses the corrected channel type."),
]

NEG = [
 R("NEG-01","R3-4","refuseguard","E0 defensive-refusal reproduction gate FAIL -> PIVOT (pre-registered)",
   "Defensive/security wording does not induce any refusal on the vulnerability-analysis task: delta RR is exactly 0 in all arms of all 3 models; gate fails and the program pivots to untrusted-context robustness.",
   "RR=0.000 all 9 model-arm cells; dRR=0.000 [0,0], McNemar p=1.0 everywhere; gate FAIL: models_completed 3/3, models_pass 0/3 (rule: dRR>=0.10, p<0.05); PASS-branch unattainable at n=20 (disclosed, config not edited post-hoc)",
   "outputs/experiments/round3_e0/gate_verdict.json (re-verified in this session); outputs/master/master_results.md E0:82-86; docs/results_master.md T1",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "The founding negative: motivates the entire pivot and the paper's framing; must keep the n=20 power disclosure verbatim."),
 R("NEG-02","R5","refuseguard","E0-V2 C5 query-relevant blocking attack: all gates NOT_SUPPORTED",
   "Query-relevant threat-intel advisories do not induce blocking/refusal in 2-3B code models (pre-registered H_A/H_B/H_C fail 0/3) - blocking-transfer fear is unsupported at this scale.",
   "RR=0.000 and benign_block=0.000 in all 3 models x 4 arms (1,200 records; 1,199 ANSWER + 1 PARTIAL); H_A/H_B/H_C NOT_SUPPORTED 0/3 (verdict.json)",
   "outputs/experiments/round5_e0v2/verdict.json + results_*.json; docs/results_master_round5.md T5; outputs/master/round5_master.json",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Second founding negative, with the scale caveat locked in the pre-registered 0/3 clause (no absence claim beyond 2-3B)."),
 R("NEG-03","R9-15","packguard","Structural refusal-absence in PackGuard domain",
   "Zero refusals across the whole PackGuard defensive-task surface - recorded as a boundary/floor condition, never as 'blocking is useless'.",
   "RR=0 on exactly 2,700 defensive-task generations 2-3B (macro pmGenDefTotal, V2-verified); n=60 safety: RR 0/360; rule: floor effect, not a capability claim",
   "paper2/p0_macros/numbers.tex; reports/round15/V2_report.md (2,700 check); reports/round9/V1_report.md §2",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "One boundary sentence in paper 2 (already in abstract/cover letter as 'RR=0/2,700 ... floor effect')."),
 R("NEG-04","R3-4","refuseguard","Refusal-monitor validity split (Qwen model-level over-refusal)",
   "Instrument-side false-refusal passes the validity floor, but Qwen itself over-refuses calibration probes - RR as a primary endpoint needs the standing caveat.",
   "monitor false_refusal 0.0 (both models, PASSES <=0.10); model-strong over-refusal: qwen 0.520, llama 0.0533 at fit; qwen calibration accuracy 0.328",
   "outputs/transformer/calibration/Qwen_Qwen2.5-Coder-3B-Instruct/full_report.json; outputs/master/master_results.md calib.*:408-429; docs/results_master.md T9",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Validity section table; E0's dRR=0 survives because over-refusal is symmetric across arms (disclosed)."),
 R("NEG-05","R4","refuseguard","Granite unsafe-compliance on REFUSE-expected probes (sanity-floor FAIL)",
   "Granite complies with 54% of unsafe probes in the neutral arm - a real model-level safety anomaly, reported as-is per protocol (no filtering).",
   "granite unsafe-compliance neutral arm 0.538 = 7/13 (defensive 0.385, security 0.462); qwen 0.154, llama 0.154 neutral",
   "outputs/experiments/round3_e0/granite2b/results.json (probe.*); docs/results_master.md:62-64, 83-84",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","APPENDIX",
   "Small-n probes (n=13) - appendix table + footnote; also feeds the granite monitor in-sample-fit disclosure."),
 R("NEG-06","R3","refuseguard","E5 stripping defenses: DRR undefined (nothing to recover) + carrier-stripping bias",
   "Post-pivot there are no refusals to recover (DRR=None, n_candidates=0), and B2/B3's recall 1.000 under C3 is by-construction carrier removal - a bias, not a recovery.",
   "DRR None (0 candidates) all 7 cells; C3|B2/B3 recall 1.000 flagged 'bias' (TP=31/31 vul because carrier removed); CUL 0.000; n=31 (9/40 skipped disclosed)",
   "outputs/experiments/round3_e5/results.json; outputs/master/master_results.md E5:231-274; docs/results_master.md T4",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","APPENDIX",
   "Keep the bias warning mandatory wherever E5 is cited; main text needs only 1 sentence (recovery endpoint undefined post-pivot)."),
 R("NEG-07","R3","refuseguard","E6 vulnerable-only stratum n.s. + benign-keep-bias",
   "The aggregate E6 significance is driven by the benign stratum; on vulnerable functions alone the effect is unresolved (p=0.5) and P1 preserves the all-vulnerable bias.",
   "discordant b10=8 = 6 benign (p=0.031) + 2 vul (p=0.5 n.s.); vul-only n=14; MCC C3: B0 +0.205 vs P1 -0.029 ('isolation is not accuracy')",
   "outputs/experiments/round3_e6/results.json#records; outputs/master/master_results.md e6.discordant.*:310-312",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Mandatory companion of POS-02 (locked wording in ROUND3_SUMMARY #4); keeping it main-text is what makes POS-02 defensible."),
 R("NEG-08","R4","refuseguard","E7 fusion pilot underpowered",
   "LLM->CodeBERT fallback coverage gain is tiny on a 0.5B pilot with reused records; per-case fallback correctness was never persisted.",
   "UAC 0.985->1.000 (+0.015; C3 +0.032), MCC 0.0789->0.0942, n_fallback_used=2 of 133; Qwen2.5-Coder-0.5B records, no_llm_called=true; tau pre-registered",
   "outputs/experiments/round3_e7/e7_fusion_results.json; outputs/master/master_results.md E7:320-343",
   "WEAK UNDERPOWERED","STANDING","APPENDIX",
   "Appendix table; main text at most one sentence ('restores full coverage in a pilot')."),
 R("NEG-09","R4","refuseguard","'Fallback decisions 2/2 correct' (paper claim, R4)",
   "Claim had no artifact: e7_fusion_results.json only records n_fallback_used=2, never per-case correctness - retracted with a regression guard added to make_figures.",
   "claim in tab_defenses.tex:37 + 05_results.tex:146; retracted to 'two fallback invocations (2 of 133 records); per-case correctness not persisted'",
   "reports/round4/ROUND4_SUMMARY.md #1 (V1-R4 catch); paper/make_figures.py guard",
   "POTENTIALLY MISLEADING","RETRACTED","RETRACTION_NOTE_IN_PAPER",
   "Ledger-only; the retraction sentence is the paper-facing residue."),
 R("NEG-10","R4","refuseguard","E4 near vs far carrier strata",
   "Near/far recall differences are small, untested, and confounded-strata were excluded - descriptive only.",
   "n=64 near / 62 far per model; recall deltas <=0.05 (e.g. qwen 0.733 vs 0.704); no significance test reported",
   "outputs/experiments/round3_e2e3/*/e4_breakdown.json; outputs/master/master_results.md E4:193-229",
   "WEAK UNDERPOWERED","STANDING","APPENDIX",
   "Appendix table; do not cite directionally in main text."),
 R("NEG-11","R6","refuseguard","B2 content-attribution underpowered (priming-like, not content-proven)",
   "Concrete-vs-generic FP-flip contrast flips sign across models and granite's CI covers 0 - no detectable content-specific trace at this power, and wording was lowered accordingly (V1-R6 MINOR-2).",
   "llama d(C-G) -0.273 [-0.458,-0.088] (headroom artefact); granite +0.267 [-0.067,+0.600] and -0.067 [-0.333,+0.200]; zero-API advisory alone flips 9/9 llama + 8-13/15 granite still-correct verdicts",
   "outputs/master/round6_bias.json bias.*.stratum.*; docs/verdict_bias.md §4; reports/round6/ROUND6_SUMMARY.md #9",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Keep the hedged sentence ('priming-like; zero-API advisory alone suffices') in main text - the sufficiency claim is the usable part; the CI discloses the residual content-effect room."),
 R("NEG-12","R5-6","refuseguard","Qwen saturation makes several qwen cells uninformative",
   "Qwen flags everything at C0 (FP=1.0, recall=1.0), so its dFP=0 and VCI=0 are ceiling artefacts, not robustness; its P3 'inertness' (2/120 pairs) rides on the same ceiling.",
   "qwen FP 1.000 at C0 all arms; VCI 0.000 (saturated); P3 qwen 2/120 pair changes (1 benign sample, both arms); ablation 0/60 flips p=1.0",
   "outputs/master/round6_bias.json; outputs/master/round5_master.json; docs/verdict_bias.md §3 bullet 3; reports/round5/ROUND5_SUMMARY.md #3 (1/98->2/98 fix)",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Mandatory footnote wherever qwen appears in a null role ('model-specificity, NOT robustness')."),
 R("NEG-13","R5-10","refuseguard","Hypothesis 'P3 harms only when an advisory is present' - REFUTED",
   "The C0xP3 control shows P3 collapses llama vulnerable recall without any advisory: the harm is intrinsic to the wrapper, not an interaction.",
   "llama C0 recall 0.967->0.233 with P3 (22 flips, exact p=4.8e-07, y_pred agreement 0.283); qwen 1.000->0.933 (2 flips, p=0.5)",
   "outputs/master/round5_master.json (control rows); docs/results_master_round5.md T6 control table; docs/verdict_bias.md §8.3",
   "OBSOLETE","SUPERSEDED","APPENDIX",
   "Keep as a documented falsification (1 sentence + ledger): good-practice example of a hypothesis killed by its own control."),
 R("NEG-14","R7","refuseguard","RQ9: reassertion harm absent at 7B, but family/scale confounded",
   "The A5 harm does not appear at 7B - supporting 'reassertion is a <=3B risk' - yet qwen-7B shares the family that was inert at 3B, so scale is not isolated; baseline and completion length caveats stand.",
   "A0 0.4746 -> A5 0.5167 (delta -0.042 = wrong direction for harm), 3 flips 1->0, exact p=0.7266; H_R1 NOT_SUPPORTED-ABSENT; caveats: same-family qwen, A0 low (subset difficulty), ~50-token completions (measured, not 512)",
   "outputs/master/round7_master.json (verdict.RQ9.H_R1 NOT_SUPPORTED-ABSENT; verified in this session); reports/round7/ROUND7_SUMMARY.md §2",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Boundary result completes the guidance story (with POS-12); all three caveats are mandatory in any sentence citing it."),
 R("NEG-15","R7","refuseguard","RQ8 llama per-family NOT_SUPPORTED 2/4 (honest anti-masking)",
   "Llama's generalization is pooled-driven: CWE-476 misses significance by one flip and CWE-190 had no headroom (C0 FP already 0.90) - reported per family, not averaged away.",
   "llama family_pass 2/4, H_G1 NOT_SUPPORTED, CWE-476 p=0.0625 (one flip short); llama FP-rate C0 0.90 on CWE-190; granite 4/4 for contrast",
   "outputs/master/round7_master.json (verdict.RQ8.llama3b.*, verified in this session); reports/round7/ROUND7_SUMMARY.md §2",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Keeping the per-family failure visible is required by charter §13 and pre-empts the cherry-picking objection."),
 R("NEG-16","R3","refuseguard","E8-Llama original headline 'B0 0.400 -> P2 0.000, p=0.00049'",
   "Measurement artifact: lexical monitor missed 11 real refusals (3 patterns + Unicode apostrophes); recomputed from raw gives B0=0.033 (1/30) and p=1.0 - claim retracted, originals preserved for audit.",
   "original 0.400 / p=0.00048828 (b10=12) vs recomputed 0.033 / p=1.0 (b10=1), n_status_changed=11; both stored (master contradictions table)",
   "outputs/experiments/round3_e8_llama3b/results.json vs recomputed/recompute_e8_monitor.json; outputs/master/master_results.md 'Contradictions':437-447; reports/round3/ROUND3_SUMMARY.md #1",
   "POTENTIALLY MISLEADING","RETRACTED","RETRACTION_NOTE_IN_PAPER",
   "Ledger-only; papers must use the recomputed file (disclosure #5 in results_master.md)."),
 R("NEG-17","R2","refuseguard","P2-cu (round-2) pushed unsafe compliance to 1.000 (refusal-suppression)",
   "The pre-fix P2 pipeline reframed unsafe prompts as authorized and schema-forced refusals into answers (0.040->1.000, 48/50 flips) - a real system-level failure that motivated the gate-first redesign.",
   "round-2 recomputed: B0 0.040 vs P2-cu 1.000 (48/50 paired flips); mechanism: gate 0/50 + reframe + retry + monitor short-circuit; fixed in round 3 (REFUSED_UNSAFE, gate-first)",
   "outputs/experiments/pilot_round2_recomputed/summary_v2.json; reports/round2/ROUND2_SUMMARY.md #3; docs/results_master.md T7",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","SUPERSEDED","APPENDIX",
   "Historical: keep 2 sentences in the design-rationale/appendix ('the fix's true value = removing refusal-suppression'); never as a current P2 number."),
 R("NEG-18","R2","refuseguard","Pilot round-2 SIUD +0.258 'first real signal' (+ E5 'B1 worse / B2-B3 restore')",
   "Runner/metrics schema mismatch (meta.pred_* vs top-level) made every verdict count as unusable; recomputed SIUD = 0.000 (C3 +0.032 [0,+0.097]) - the claim and the whole E2/E5 table were withdrawn.",
   "claimed SIUD(C0-C2a) +0.258 -> recomputed 0.000; E2 framing +0.132 -> 0.000; E5 'recovery' table withdrawn with it",
   "reports/round2/ROUND2_SUMMARY.md §1 claim 2 + §2 #1; outputs/experiments/pilot_round2_recomputed/summary_v2.json",
   "POTENTIALLY MISLEADING","RETRACTED","RETRACTION_NOTE_IN_PAPER",
   "Ledger-only; canonical SIUD numbers live in the round-3 master (POS-01/NEG-06)."),
 R("NEG-19","R8-11","packguard","'Text (TF-IDF) degrades under federation' (R8 dF1 -0.101 p=.001; R9 grid p=3.8e-6)",
   "Retracted twice: first as a feature-pipeline artifact (R8), then as a baseline artifact (pooled-vocabulary fit + undertrained central baseline); under the corrected protocol the effect vanishes.",
   "R8: group/tfidf dF1 -0.101 [-0.155,-0.047] p=.001; R11 retraction: hashing stateless baseline p=.312 (group) / .404 (random) ns, 0/360 rows recall>=0.999; old-vs-new kept via macros",
   "reports/round8/F_report.md §1 P1e; reports/round11/F_report.md §1 T3(b); outputs/packguard/fl_multiseed/grid_results.json (audit substrate)",
   "OBSOLETE","RETRACTED","RETRACTION_NOTE_IN_PAPER",
   "Paper 2 keeps the controlled retraction paragraph ('text and graph features are both federation-robust under the corrected protocol'); grid artifacts preserved unchanged for audit."),
 R("NEG-20","R8","packguard","'FedAvg harms the minority client' (pypi F1 .588 vs .757)",
   "Disappeared after the feature bugs were fixed (pypi .875 both FL and centralized on group split) - an artifact, not a property of FL on this data.",
   "R8: pypi F1 FL .588 vs central .757 -> post-fix .875 vs .875; recorded in paper as a retracted finding",
   "reports/round8/F_report.md §1 P1e ('Finding trung thực đáng chú ý'); outputs/packguard/fl/results.jsonl",
   "POTENTIALLY MISLEADING","RETRACTED","RETRACTION_NOTE_IN_PAPER",
   "Ledger-only; one clause inside the paper-2 retraction paragraph."),
 R("NEG-21","R8-11","packguard","FedProx(mu=.01) == FedAvg bit-identical 160/160",
   "Not an algebraic finding: a routing bug ran FedProx(.01) in both arms; after the fix mu separates in probabilities, not F1 (descriptive).",
   "40/40 pairs identical <1e-12 (R9); R11 root cause: mu not routed per-algo, legacy_mu_routing flag, 12 unit tests; mu-sweep dF1 +0.0043..+0.0048 p=.084-.475 (descriptive)",
   "reports/round9/V1_report.md A3(c); reports/round11/F_report.md §1 T3(d); configs AMENDMENT-5",
   "OBSOLETE","SUPERSEDED","APPENDIX",
   "Threats-to-validity paragraph; the corrected mu-sweep is descriptive-only."),
 R("NEG-22","R9-11","packguard","Centralized collapse cell (F1 .375, seed 20260923)",
   "One 1/40 grid cell collapsed; reproducible bit-exact (real, not a runner bug) but later re-attributed to undertraining - the strong baseline never collapses (0/80 converged).",
   "R9: F1 .3750 reproduced d=0.00e+00; R11: collapse re-attributed ('undertraining, not data structure'), random/graph central .835+/-0.113 -> .887+/-0.020, max n_iter 69, min F1 .769",
   "reports/round9/V1_report.md A3(a); reports/round11/F_report.md §1 T3(d)",
   "WEAK UNDERPOWERED","SUPERSEDED","APPENDIX",
   "Appendix/sensitivity note only; keep the reproducibility story (it is a good determinism anecdote)."),
 R("NEG-23","R9","packguard","TF-IDF FedAvg degenerate all-malicious predictor",
   "tfidf-FedAvg collapsed to predicting 'malicious' for everything (recall 1.0, precision = base rate) - a real measurement diagnosis under the old pipeline, absent under the corrected protocol.",
   "recall 1.0 in 20/20 cells; precision .6446 = 78/121 base rate; F1 = 2*78/(121+78) exactly, all seeds; corrected protocol: 0/360 rows recall>=.999",
   "reports/round9/V1_report.md A3(b); reports/round11/F_report.md T3(b) (0/360 check)",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","SUPERSEDED","APPENDIX",
   "Appendix/measurement-integrity note; never cite the old tfidf-FL numbers without this context."),
 R("NEG-24","R11","packguard","Centralized wins on the leakage-prone random split (TOST FAIL, directional)",
   "Mandatory disclosure: on random splits the strong baseline beats FedAvg by .016 F1 - the equivalence claim is split-scoped and 'FL is never worse' is not claimed.",
   "random/graph dF1 -0.0160, exact p=.0062, Holm .0247; TOST CI entirely below 0 (directional); primary group split PASS both features",
   "outputs/packguard/p0/p0_results.json; reports/round11/F_report.md §1 T3(c) + §4 framing 2",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Keep verbatim in main results ('a small cost only under the leakage-prone random split') - removing it would be soft-washing."),
 R("NEG-25","R8-15","packguard","KB ablation neutral / mixed-sign",
   "LLM-KB features do not move FedAvg and only trend on the centralized minority subgroup - below seed noise, never claimed significant.",
   "FedAvg F1 .923->.922 (neutral); centralized .928->.938, all gain on pypi subgroup n=29 (descriptive only); final status: 'KB neutral (mixed-sign, < seed-std)'; 62 tail APIs unsure by construction (disclosed)",
   "outputs/packguard/fl/results.jsonl (--with-kb rows); reports/round8/F_report.md §1 P2; SUBMISSION.md §2 claim 6",
   "NULL LOW-VALUE","STANDING","APPENDIX",
   "Appendix table + 1 sentence; scoped KB-ablation 20-seed remains queued future work."),
 R("NEG-26","R12","packguard","D1 defense cost on llama (restores nothing)",
   "The same strip that fully neutralizes granite gives llama zero restoration: its 4 lost detections are byte-identical snippets of one package family whose own comment the strip removes - a pre-registered possible outcome.",
   "llama .167 -> .042 under attack -> .042 defended (gain 1/loss 1; the +1 is a NEW artifact-lab detection, not recovery); 4 losses = 4 versions of @antoncallahan/aws-user-helper (1/19 families every condition)",
   "outputs/packguard/defense/defense_analysis.json (per_model_pointers); reports/round12/F_report.md §3",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "First-class cost paragraph beside POS-17 - the honest framing reviewers reward; keep the tinywallet example."),
 R("NEG-27","R12","packguard","Pooled attack+defense numbers hide opposite per-model outcomes; all p descriptive",
   "The pooled block (n=47) averages a granite win and a llama loss; every p in the batch is descriptive (min .125) and the attack arm carries no benign rows (FP not re-measured; n=100: 2/100, all granite).",
   "pooled recall P0 .417 / P2 .438 / P2D1 .340, McNemar P2vsP2D1 p=.219 (1 vs 5); min exact p in file .125; 0-discordant cells p=1.0 by construction; CP upper ~12%",
   "outputs/packguard/defense/defense_analysis.json (descriptive_power field); reports/round12/F_report.md §1.2, §3",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Keep per-model as the primary read + one pooled sentence with the caveat; FP numbers always cited from the n=100 expansion with 'not re-measured here'."),
 R("NEG-28","R13","packguard","LCO family-shift: two-directional null (no robustness ranking)",
   "Under MinHash cluster hold-outs both feature blocks degrade and their difference is null at good power - the robustness-ranking question the paper itself raised is answered 'not established'.",
   "dd = -0.0095+/-0.0803, exact Wilcoxon p=.368, 95% CI [-0.047,+0.028]; graph block -0.0383 [-0.070,-0.007], text -0.0289 [-0.070,+0.012]; power ~=0.75 at d=.05; equivalence at +/-0.02 NOT established (passes only at .05); metadata baseline degrades similarly",
   "outputs/packguard/lco/lco_results.json (480 rows) + summary.md; reports/round13/F_report.md §1 (F independently recomputed all cells)",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Keep as the honest null paragraph (already in §5.4); the '+/-0.02 equivalence would pass at .05' sentence must stay."),
 R("NEG-29","R14","packguard","GuardDog LCO advantage is 1-seed and sign-flips",
   "GuardDog tops the hardest LCO seed (t0.30) but loses at t0.50 and shares the corpus source with the rules - 'comparable, not superior' is the only allowed wording.",
   "LCO t0.30: GD .857/.876 vs learned .747-.835 (1 seed); t0.50 same seed: GD .8550 < graph .8980 / hashing .8800; same-origin DataDog bias registered before scan",
   "outputs/packguard/guarddog/metrics.json; reports/round14/W_report.md §3.2 (caveats 1,5)",
   "WEAK UNDERPOWERED","STANDING","APPENDIX",
   "Appendix note + footnote on the comparison table; 20-seed LCO recompute is cheap (findings already exist) and queued."),
 R("NEG-30","R14","packguard","GuardDog recall ceiling + FN structure",
   "Rule-based detection misses ~21% of malicious packages; most FNs fire no high rule at all - precision-first triage, not recall-first.",
   "recall .78-.80 all scopes; 81/389 malicious score 0; corrected decomposition (V-audit): 25/81 trigger no rule even at medium/low, 56/81 only medium/low rules; FP only 17/602 (CLI tools triggering filesystem-read/process-memory)",
   "outputs/packguard/guarddog/{findings.jsonl,metrics.json}; reports/round14/W_report.md §3.3 + [CORRECTED-R14] header (56/81 score-0 was the complement - fixed before paper)",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","CORRECTED","APPENDIX",
   "Appendix diagnostics; the corrected 25/81 vs 56/81 split must be the cited version."),
 R("NEG-31","R15","packguard","MalGuard-style comparison: no equivalence and no significant difference after Holm",
   "Both directions are unresolved statistically: 8/8 TOST FAIL at +/-0.02, raw p<.05 in 3 cells but 0/8 survive Holm - so neither 'worse, significant' nor 'equivalent' may be written.",
   "malguard-vs-graph dF1 -0.0216 p=.0441 -> Holm .3084; -0.0169 p=.0441 -> .3084; -0.0227 p=.0362 -> .2899; combined +0.0150 p=.1054; per-seed McNemar 5/20 seeds p<.05 (b01 12.75 vs b10 9.75)",
   "outputs/packguard/malguard_style/aggregate.json; reports/round15/W1_report.md §3.2 + V1_report.md §3 (reproduced to 1e-9)",
   "WEAK UNDERPOWERED","STANDING","KEEP_MAIN",
   "Keep the hedged ablation sentence; the PyPI gap (descriptive) is the interesting hook for future work, not a claim."),
 R("NEG-32","R13","packguard","Benign hard-negative expansion (+200 random npm)",
   "Only 17/200 show hard-negative profiles; explicitly a data-pack for the next round, not robustness evidence, and outside the registered corpus.",
   "200/200 sha256 verified; 17/200 hard-negative (2 hook / 16 network); manifest benign_expansion_v1.json (14.8MB integrity anchor, policy exception documented)",
   "data/packguard/manifests/benign_expansion_v1.json; reports/round13/F_report.md §5 P2-11b",
   "NULL LOW-VALUE","STANDING","APPENDIX",
   "One appendix sentence ('data-pack, not evidence'); paper correctly does not cite it as corpus."),
 R("NEG-33","R1","refuseguard","'e0-e8 dry-run error-free' (mock corpus only) + C++ grammar hard-code crash",
   "The round-1 dry-run success claim held only on a synthetic corpus; on the real PrimeVul manifest 6/9 runners crashed (65% C++ vs c-only grammar). Fixed: 9/9 exit 0, parse coverage 34.9%->74.6%.",
   "6/9 crash pre-fix -> 9/9 OK; parse coverage 34.9%->74.6%; claim flagged [CRITICAL] by V2",
   "reports/round1/ROUND1_SUMMARY.md #1; reports/round1/S_report.md",
   "OBSOLETE","SUPERSEDED","LEDGER_ONLY",
   "Audit-trail history; no paper text cites the dry-run claim anymore."),
 R("NEG-34","R1","refuseguard","Measurement/instrument defects batch (VD-S wrong, monitor blind spots, bib errors, seq-len 1024)",
   "Round-1 audit caught a fake VD-S (was not FNR@FPR<=0.5%), monitor missing refusal patterns, 5 wrong bib entries, and an impossible CodeBERT seq-len recommendation - all fixed with tests.",
   "vd_s reimplemented as official FNR@FPR<=0.5%; monitor +3 patterns + lexical_floor; 5 bib entries corrected with [CORRECTED]; seq-len fixed to truncate @512 (cap 512 hard)",
   "reports/round1/ROUND1_SUMMARY.md #4,5,6,8; docs/eda_primevul.md [CORRECTED] block",
   "POTENTIALLY MISLEADING","CORRECTED","LEDGER_ONLY",
   "Instrument-provenance history; the fixed instruments are what all standing numbers rest on."),
 R("NEG-35","R2","refuseguard","Lexical intent-gate limits (pre-fix 0/50; scoring-half paraphrase 1/50)",
   "The lexical safety gate missed all 50 real unsafe probes before the pattern fix and still catches only 1/50 scoring-half paraphrases - a disclosed instrument limit requiring a model-based gate.",
   "pre-fix 0/50 on real unsafe probes (mock 4/4 was overfit); post-fix 30/30 unsafe, 0/30 safe false-block; scoring half blocked 1/50 (49/50 escaped) - direction corrected in R4 per the actual file",
   "outputs/experiments/intent_gate_v2_measurement.json; reports/round2/ROUND2_SUMMARY.md #5; reports/round4/ROUND4_SUMMARY.md #7 (wording fix)",
   "NEGATIVE BUT SCIENTIFICALLY USEFUL","STANDING","KEEP_MAIN",
   "Mandatory footnote wherever the P2 gate's 30/30 is cited (POS-03); keeps the safety claim scoped to the gate, not the lexicon."),
 R("NEG-36","R10","refuseguard","Fig. 8(a) plotted wrong series (layout pass found it)",
   "The paper-1 figure showed an unexplained Llama per-family band absent from Table 8; redrawn from the token map with cross-asserts against round7_master so figure and table cannot drift.",
   "fig_round7() rewritten: panel (a) = exactly Table-8 granite series (C0 0.050/0.000/0.200/0.000; C5_near 0.700/0.750/0.650/0.700); 41/41 token verify PASS",
   "reports/round10/LAYOUT_report.md X4; paper/make_figures.py (fig_round7 asserts)",
   "POTENTIALLY MISLEADING","CORRECTED","LEDGER_ONLY",
   "Ledger-only; the guard (assert-equal-before-plot) is the durable fix."),
 R("NEG-37","R7","refuseguard","'Fully fresh relative to every bench' bridge-overlap claim (RQ8 bench)",
   "False: bench_attack_v2 overlaps prior bridges (22 ids via round-2 bridge, 16 via round-1); corrected in the manifest with a [CORRECTED-R7] block; sha unchanged.",
   "overlap 0 claimed -> 22/16 ids actual; EXEC fixed key records->samples; manifest corrected with verification",
   "reports/round7/ROUND7_SUMMARY.md #1; bench_attack_v2 manifest",
   "POTENTIALLY MISLEADING","CORRECTED","LEDGER_ONLY",
   "Ledger-only; disclosure blocks carry the correction."),
 R("NEG-38","R3-15","both","Bookkeeping/count corrections (generations, wall-clock, tests, misc)",
   "Recurring audit catches that keep provenance honest; none change any scientific verdict: budget 619->488 (R3), 1,546->1,378 and 1,200=1,032+168 cache (R5), 703->834 incl. 131 polluted (R6), 16min->11min and 1/98->2/98 (R5), 405->408 tests (R5), 603-vs-602 flat-zip explained (R8), n_malicious_total 35->30 meta (R9), 56 vs 63 placeholders (R6), '16 minutes' family, safety scope 30->16->10 and KB 120->60 (R8).",
   "see summary; each has an inline correction marker or master assert (e.g. collect_master_round5.py asserts 1,378)",
   "reports/round{3,5,6,8,9}/*_report.md + ROUND*_SUMMARY corrections tables; scripts/collect_master_round5.py asserts",
   "NULL LOW-VALUE","CORRECTED","SANITY_CHECK_1LINE",
   "Represent as one provenance sentence + this ledger; no individual correction needs paper text."),
 R("NEG-39","R1-15","both","Planned-but-NOT-RUN items (adaptive attacks, repo-level realism, frontier/8B, human-kappa, OSF, FP-directed arm, validation-locked thresholds)",
   "Charter §4 checklist items with no result in rounds 1-15: no adaptive red-team round (C5 is static query-relevant advisory), no repository-level realism experiment; frontier-model and 7-8B A5 arms deferred (directive <4B); KB human-kappa, OSF timestamp, FP-directed advisory arm and validation-locked thresholds blocked/queued - all disclosed as future work, none cited as evidence.",
   "adaptive: not run; repo-level: not run (roadmap REV-4); A5@7-8B: deferred (weights removed, <4B); KB kappa: blocked (2 annotators); OSF: blocked (account); frontier: blocked (API key) - runner ready (scripts/frontier_safety_runner.py); FP-directed arm + validation-locked thresholds: queued (paper A.6)",
   "FINAL_STATUS.md §2; SUBMISSION.md revision table REV-1..6; reports/round13/F_report.md §5 (P1-7/P1-8 blocked); reports/round15/W2_report.md §4.4 (human-kappa artifact untraceable in repo)",
   "NULL LOW-VALUE","NOT_RUN","KEEP_AS_LIMITATION",
   "Record explicitly so the §4 checklist is answered honestly: these are limitations/future work, never results; the 7B family-confound (NEG-14) is the closest measured evidence on scale."),
]

os.makedirs(os.path.dirname(os.path.abspath(__file__)), exist_ok=True)
base = os.path.dirname(os.path.abspath(__file__))
for name, rows in (("POSITIVE_RESULTS_LEDGER.csv", POS), ("NEGATIVE_RESULTS_LEDGER.csv", NEG)):
    path = os.path.join(base, name)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLS)
        w.writeheader()
        w.writerows(rows)
    print(f"{name}: {len(rows)} rows")
print(f"total: {len(POS)+len(NEG)}")
