import csv, os

path = "/Users/macbook/.zcode/workspace/default/refuseguard/RESEARCH_STATE/LITERATURE_MATRIX.csv"
exists = os.path.exists(path)
print("pre-existing file:", exists)

header = ["lit_id","subtopic","arxiv_id","title","authors_short","year","arxiv_date",
          "one_line_contribution","method","evaluation","key_numbers",
          "relevance_to_refuseguard","novelty_implication","verification","source_url"]

FULL = "FULL abstract via mcp__arxiv__get_abstract 2026-09-30"
SNIP = "search snippet via mcp__arxiv__search_papers 2026-09-30"

rows = [
# --- Indirect PI: attacks, foundations, benchmarks ---
["PI-01","indirect-PI-benchmark","2403.02691","InjecAgent: Benchmarking Indirect Prompt Injections in Tool-Integrated Large Language Model Agents","Zhan, Liang, Ying, Kang","2024","2024-03-05",
 "Benchmark of IPI on tool-integrated agents: 1,054 test cases, 17 user tools, 62 attacker tools; direct-harm vs private-data-exfiltration intentions.",
 "Test cases with injected instructions in tool-returned content; strengthened 'hacking prompt' reinforcement setting.",
 "30 LLM agents evaluated.",
 "ReAct GPT-4 vulnerable 24% of the time; reinforced attacker prompt nearly doubles ASR.",
 "Closest structural analog to our C2/C3 advisory-corruption setting but in tool agents; their reinforcement setting parallels our strengthened advisories. No vulnerability-analysis task anywhere.",
 "Injection-into-analysis-pipeline is benchmarked for tools, NOT for code-vulnerability verdicts — our task axis is uncovered.",
 FULL,"https://arxiv.org/abs/2403.02691"],
["PI-02","indirect-PI-benchmark","2406.13352","AgentDojo: A Dynamic Environment to Evaluate Prompt Injection Attacks and Defenses for LLM Agents","Debenedetti, Zhang, Balunovic, Beurer-Kellner, Fischer, Tramer","2024","2024-06-19",
 "Extensible agent environment (97 tasks, 629 security test cases) for evaluating attacks AND defenses AND adaptive attacks, not a static suite.",
 "Task-suite + attack/defense plug-in harness; hosts later CaMeL numbers and adaptive-attack studies.",
 "State-of-the-art LLMs in agentic tasks (email, e-banking, travel).",
 "SOTA LLMs fail many tasks even unattacked; existing attacks break some but not all security properties.",
 "The de-facto eval infrastructure our defense comparisons would be judged against; our paired P0/P2 protocol is a static analog of its dynamic design.",
 "No code-vulnerability-analysis task suite exists inside AgentDojo — porting our task family into it is a concrete, fundable gap.",
 FULL,"https://arxiv.org/abs/2406.13352"],
["PI-03","indirect-PI-defense-marking-provenance","2403.14720","Defending Against Indirect Prompt Injection Attacks With Spotlighting","Hines, Lopez, Hall, Zarfati, Zunger, Kiciman","2024","2024-03-20",
 "Family of prompt-engineering transforms (delimiting, data marking, encoding) giving a continuous provenance signal so the LLM can tell input sources apart.",
 "Input transformations providing reliable continuous provenance signal; evaluated as IPI defense.",
 "GPT-family models on IPI benchmarks.",
 "ASR from >50% down to below 2% with minimal impact on task efficacy.",
 "This is the cheapest published baseline for our P3 provenance wrapper — a wrapper-level provenance marking prior that must be cited and ideally compared.",
 "Provenance-by-marking is prior art; our differentiator must be verdict-corruption recovery + utility cost (D1-style), not injection prevention.",
 FULL,"https://arxiv.org/abs/2403.14720"],
["PI-04","indirect-PI-realworld","2509.10540","EchoLeak: The First Real-World Zero-Click Prompt Injection Exploit in a Production LLM System","Reddy, Gujral","2025","2025-09-06",
 "Case study of CVE-2025-32711, a zero-click PI vulnerability in a production enterprise LLM assistant bridging internal and external data.",
 "Forensic analysis of a real CVE in an LLM-integrated product.",
 "Production LLM assistant (enterprise workflow).",
 "Real-world exploit chain documented (CVE-2025-32711).",
 "Deployment-side evidence that untrusted-content corruption of LLM pipelines is exploitable in practice, not just in benchmarks.",
 "Supports external validity of our threat model; no vuln-analysis corruption angle.",
 SNIP,"https://arxiv.org/abs/2509.10540"],
["PI-05","indirect-PI-overview","2507.13169","Prompt Injection 2.0: Hybrid AI Threats","McHugh, Sekrst, Cefalu","2025","2025-07-17",
 "Overview of PI evolution including multimodal and agentic hybrid threats, from 2022 responsible disclosures onward.",
 "Survey-style threat synthesis.",
 "Cross-cutting.",
 "n/a (threat taxonomy).",
 "Background framing only.",
 "Low.",
 SNIP,"https://arxiv.org/abs/2507.13169"],
["PI-06","mechanism","2603.12277","Prompt Injection as Role Confusion","Ye, Cui, Hadfield-Menell","2026","2026-02-22",
 "Traces prompt injection to role confusion: models infer text source from how it sounds, not from the labeled role (<user>/<tool>).",
 "Mechanism analysis of role attribution in single text-stream LLMs.",
 "LLMs processing role-partitioned streams.",
 "A webpage command hijacks an agent when it sounds authoritative (per abstract).",
 "Mechanism-level explanation of WHY our strip (D1) and reassertion (A5) mitigations are partial: corruption is perceptual, not just lexical.",
 "Mechanism papers strengthen our framing; our AST/semantic-level isolation story should engage with role-confusion evidence.",
 SNIP,"https://arxiv.org/abs/2603.12277"],
["PI-07","agent-PI-persistence","2606.04425","What If Prompt Injection Never Left? Rethinking Agent Security through Cross-Session Stored Prompt Injection","Xie et al.","2026","2026-06-03",
 "PI that persists in agent memory/filesystem/state across sessions; persistent state reshapes the security boundary.",
 "Threat model + analysis of stored-injection lifecycle in agentic systems.",
 "Agentic systems with long-lived contextual artifacts.",
 "n/a in snippet.",
 "Adjacent: our corrupted-verdict persistence across a session is a milder cousin; not our core axis.",
 "Low-medium for our matrix; watch for stored-advisory-corruption follow-ups.",
 SNIP,"https://arxiv.org/abs/2606.04425"],
["PI-08","agent-PI-MCP","2602.20720","AdapTools: Adaptive Tool-based Indirect Prompt Injection Attacks on Agentic LLMs","Wang et al.","2026","2026-02-24",
 "Adaptive tool-based IPI through MCP data services against agentic LLMs.",
 "Adaptive injection crafted through MCP-integrated external data services.",
 "MCP-based agentic LLMs.",
 "n/a in snippet.",
 "MCP-era adaptive attacker: the attacker class our NEG-39 adaptive red-team question should inherit from.",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2602.20720"],
# --- Code-context PI ---
["PI-09","code-context-PI","2510.23675","QueryIPI: Query-agnostic Indirect Prompt Injection on Coding Agents","Xie, Liu, Luo, Zhang, Zhang, Yuan, Li, Chen, Wang, She","2025","2025-10-27",
 "Query-agnostic IPI on IDE coding agents: payloads optimized into tool descriptions using invariant prompt context; works under arbitrary user queries.",
 "Automated framework: seed generation aligned with agent conventions + iterative prompt-based blackbox optimization; reflection to defeat refusals.",
 "Five simulated coding agents; transfer to real-world coding agents.",
 "Up to 87% success vs best baseline 50%; generated malicious descriptions transfer to real coding agents.",
 "Strongest code-domain IPI evidence: code-context payloads are optimizable and transfer — directly raises the realism bar for our repo-level/untrusted-code-context claims (NEG-39).",
 "Attack-side prior in the coding domain; our defense-side (verdict recovery) work remains distinct but MUST cite and ideally test against query-agnostic injections.",
 FULL,"https://arxiv.org/abs/2510.23675"],
["PI-10","code-context-PI","2603.21642","Are AI-assisted Development Tools Immune to Prompt Injection?","Huang, Huang, Milani Fard","2026","2026-03-23",
 "First empirical tool-poisoning analysis across 7 real MCP clients (Claude Desktop, Claude Code, Cursor, Cline, Continue, Gemini CLI, Langflow).",
 "Empirical security-feature audit: static validation, parameter visibility, injection detection, warnings, sandboxing, audit logging.",
 "7 widely used MCP clients.",
 "Significant disparities; e.g. Cursor highly susceptible to cross-tool poisoning, hidden-parameter exploitation, unauthorized tool invocation.",
 "Deployment evidence that developer tools currently lack systematic untrusted-content defenses — motivates defense work in our exact domain.",
 "Confirms practitioner-side gap; no defense proposal — leaves the defense slot open.",
 FULL,"https://arxiv.org/abs/2603.21642"],
["PI-11","code-context-PI","2605.25871","How Agentic AI Coding Assistants Become the Attacker's Shell","Liu, Zhao, Lyu, Zhang, Wang, Lo","2026","2026-05-25",
 "Hidden instructions in unvetted external artifacts hijack agentic coding assistants that edit files, run commands, access internet.",
 "Attack-surface analysis of artifact-borne instructions in coding agents.",
 "Agentic coding assistants.",
 "n/a in snippet.",
 "Same threat family as our untrusted in-package/advisory content (PackGuard), but targeting agent actions rather than analysis verdicts.",
 "Adjacent prior for PackGuard framing; verdict-corruption (not action-hijack) remains our axis.",
 SNIP,"https://arxiv.org/abs/2605.25871"],
["PI-12","code-context-PI","2608.14876","Workspace Topology as an Attack Vector in Agentic Coding Assistants","Day et al.","2026","2026-08-14",
 "Malicious third-party code ingestion via workspace layout/filesystem access as an attack surface of coding assistants.",
 "Attack-vector analysis in real developer workflows.",
 "Agentic coding assistants with broad filesystem access.",
 "n/a in snippet.",
 "Repo-level realism evidence (our charter question on repository-level realism).",
 "Medium; attack-side context.",
 SNIP,"https://arxiv.org/abs/2608.14876"],
["PI-13","code-context-PI","2408.04194","FDI: Attack Neural Code Generation Systems through User Feedback Channel","Sun, Du, Luo, Song, Li","2024","2024-08-08",
 "Feedback-channel attack on neural code-generation services: user-submitted feedback injects to poison subsequent generations.",
 "Injection through the user-feedback channel of code-generation as-a-service.",
 "Neural code generation systems (remote services).",
 "n/a in snippet.",
 "Another code-domain untrusted channel; distinct from advisory/appended-context channel we corrupt.",
 "Low-medium; useful in related-work map of code-context PI.",
 SNIP,"https://arxiv.org/abs/2408.04194"],
["PI-14","code-context-PI","2601.17548","Prompt Injection Attacks on Agentic Coding Assistants: A Systematic Analysis of Vulnerabilities in Skills, Tools, and Protocol Ecosystems","Maloyan, Namiot","2026","2026-01-24",
 "Systematic vulnerability analysis of Claude Code / Copilot / Cursor-class assistants incl. skill-based architectures.",
 "Systematic analysis across skills, tools, protocol ecosystems.",
 "Major agentic coding assistants.",
 "n/a in snippet.",
 "Completes the code-context attack-side map our related work must cover.",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2601.17548"],
# --- StruQ / CaMeL / trusted-data separation ---
["PI-15","trusted-data-separation","2402.06363","StruQ: Defending Against Prompt Injection with Structured Queries","Chen, Piet, Sitawarin, Wagner","2024","2024-02-09",
 "Structured queries: two-channel (prompt vs data) format + structured instruction-tuned LLM trained to ignore instructions appearing in the data channel.",
 "Secure front-end formatting + fine-tuning strategy augmenting instruction data with in-data instructions the model learns to ignore.",
 "LLM-integrated applications; benchmark IPI tasks.",
 "Significantly improves resistance with little or no utility impact (per abstract).",
 "Canonical trusted/untrusted channel-separation defense; contrast class for our training-free D1-strip on 2-3B open models. Labeled USENIX Security 2025 by the 2507.07417 abstract.",
 "Fine-tuned separation is breakable whitebox (see 2507.07417) — we should not claim channel separation as our novelty; our contribution is corruption detection/recovery without retraining.",
 FULL,"https://arxiv.org/abs/2402.06363"],
["PI-16","trusted-data-separation","2503.18813","Defeating Prompt Injections by Design (CaMeL)","Debenedetti, Shumailov, Fan, Hayes, Carlini, Fabian, Kern, Shi, Terzis, Tramer","2025","2025-03-24",
 "CaMeL: protective system layer; control+data flows extracted from the trusted query so untrusted data cannot impact program flow; capabilities + policies on tool calls prevent exfiltration.",
 "System-level control-flow integrity around the LLM + capability-based data-flow policies.",
 "AgentDojo tasks.",
 "77% of tasks solved with provable security vs 84% undefended.",
 "The strongest published trusted-data separation; sets the reviewer bar for any 'secure-by-design' claim. Our setting has no tool-call channel (verdict output instead), so CaMeL does not directly apply — that difference is our opening.",
 "High novelty bar for system-level defenses; any provenance-partition defense claim must position against CaMeL explicitly.",
 FULL,"https://arxiv.org/abs/2503.18813"],
["PI-17","trusted-data-separation","2509.25926","Preventing Prompt Injection with Type-Directed Privilege Separation","Jacob, Alghamdi, Hu, Alomair, Wagner","2025","2025-09-30",
 "Convert untrusted data into curated data types with limited scope/content so injection becomes impossible; expands task coverage of system-level defenses.",
 "Type-directed privilege separation; model-agnostic; motivated explicitly by adaptive-attack fragility of detectors and fine-tuning.",
 "Several case studies.",
 "Systematic prevention with strong non-trivial utility (per abstract).",
 "Typing-based sanitization is a principled version of what PackGuard AST-sanitization does informally; direct conceptual neighbor.",
 "Medium-high: our sanitization must cite this and state what it adds (measured corruption-recovery, verdict channel).",
 FULL,"https://arxiv.org/abs/2509.25926"],
["PI-18","trusted-data-separation-theory","2606.27567","On the Inseparability of Instructions and Data in Shared-Embedding Sequence Models","Pant, Lohani, Kumar","2026","2026-06-25",
 "Proves perfect PI prevention is mathematically impossible in shared-embedding pipelines lacking enforced control-data separation (provenance-recovery impossibility, control-path exposure, finite-coverage invariance gap).",
 "Formal Prompted Action Model; impossibility proofs grounded in measurements on production tokenizers/models; von Neumann code-data analogy.",
 "Production tokenizers and models (grounding measurements).",
 "Structural result: in-pipeline classification/alignment cannot eliminate PI; architectural separation required.",
 "Theoretical license for our core negative-flavored finding: prompt-level defenses (strip, reassertion) are structurally partial — cite as support for why recovery/abstention is the right target.",
 "If we ever claim a 'fix', this paper bounds what claims are honest; our recover-and-detect framing is consistent with it.",
 FULL,"https://arxiv.org/abs/2606.27567"],
["PI-19","trusted-data-separation","2607.05277","Untrusted Content Masking for Web Agents with Security Guarantees","Nikolic, Zverev, Rando, Jagielski, Debenedetti, Tramer","2026","2026-07-06",
 "Masks untrusted content to preserve the strict trusted-instruction/untrusted-data separation that guarantee-providing defenses rely on, for environments (web) where separation is not natural.",
 "Content masking to restore isolation guarantees in text/tool-use environments.",
 "Web-agent environments.",
 "n/a in snippet.",
 "Bridge between CaMeL-style guarantees and messy real content — same goal as our provenance partition of advisory text.",
 "Medium-high.",
 SNIP,"https://arxiv.org/abs/2607.05277"],
["PI-20","trusted-data-separation","2607.19595","Twin Agent: Context Residual Compression for Privilege Separated Agents","Hu, Jacob, Huang, Chen, Li, Wagner","2026","2026-07-21",
 "Compresses the untrusted-context residual in secure-by-design (privilege-separated) agents to mitigate their utility cost.",
 "Context residual compression layered on privilege separation.",
 "Privilege-separated LLM agents.",
 "n/a in snippet.",
 "Directly addresses the guarantees-vs-utility tradeoff that our D1-vs-clean-utility cost measured on llama mirrors.",
 "Medium-high: utility-recovery for secure designs is an active thread we can join with measured numbers.",
 SNIP,"https://arxiv.org/abs/2607.19595"],
["PI-21","trusted-data-separation-marking","2401.07612","Signed-Prompt: A New Approach to Prevent Prompt Injection Attacks Against LLM-Integrated Applications","Suo","2024","2024-01-15",
 "Early cryptographic marking of prompt provenance so applications can distinguish instruction vs data.",
 "Signing of user prompts; downstream handling keyed on signatures.",
 "LLM-integrated applications.",
 "n/a in snippet.",
 "Provenance-marking prior art antedating Spotlighting for our P3 lineage.",
 "Low-medium; historical anchor only.",
 SNIP,"https://arxiv.org/abs/2401.07612"],
["PI-22","trusted-data-separation-provable","2502.05174","MELON: Provable Defense Against Indirect Prompt Injection Attacks in AI Agents","Zhu, Yang, Wang, Guo, Wang","2025","2025-02-07",
 "Dual-model mutual verification: agent output is cross-checked by a second model pass to provably counter IPI.",
 "Two-model verification protocol.",
 "LLM agents under IPI.",
 "n/a in snippet.",
 "Two-pass verification is structurally similar to our trusted-verifier / disagreement-detection candidate direction (charter seed).",
 "Must cite when proposing verifier-based recovery; our code-grounded (AST/CFG) verifier differs from their LLM-only verifier.",
 SNIP,"https://arxiv.org/abs/2502.05174"],
# --- Provenance ---
["PI-23","provenance-architecture","2609.21088","Origin Is All You Need: Provenance-Aware Transformers for Structural Trust-Boundary Separation","Zhang, Huang, Gu","2026","2026-09-17",
 "Per-token ring ID for origin + origin embeddings, learnable origin attention bias and origin scale; structural authoritative vs non-authoritative boundary during generation.",
 "Architecture modification + two-stage fine-tuning to teach origin semantics under ring constraints.",
 "Released pretrained models, IPI in/out-of-distribution.",
 "Maintains IPI resistance in- and out-of-distribution with utility comparable to base model (per abstract).",
 "The architectural endgame of our prompt-level P3 provenance wrapper; explains what P3 approximates from outside the model.",
 "HIGH for our provenance thread: nearest architectural prior; our wrapper is the training-free approximation — position explicitly, and consider it as the 'next step' we enable.",
 FULL,"https://arxiv.org/abs/2609.21088"],
["PI-24","provenance-granularity","2605.11039","The Granularity Mismatch in Agent Security: Argument-Level Provenance Solves Enforcement and Isolates the LLM Reasoning Bottleneck","Fan, Li, Tian, Wang, Li, Wang","2026","2026-05-11",
 "Mediates trust at tool-argument level instead of whole-invocation level, resolving brittle allow/block choices in mixed-trust workflows.",
 "Argument-level provenance enforcement.",
 "Tool-using agents on untrusted webpages/emails/files/API outputs.",
 "n/a in snippet.",
 "Granularity framing maps onto our context-unit-level provenance partition (MinHash units in P2-11).",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2605.11039"],
["PI-25","capability-policy-provable","2602.11416","Optimizing Agent Planning for Security and Autonomy","Kolluri, Costa, Kopf, Niessen, Russinovich, Tople, Zanella-Beguelin","2026","2026-02-11",
 "Deterministic system-level defenses provably blocking unsafe actions; optimizes agent planning so the utility cost of guarantees drops.",
 "Confidentiality/integrity policy enforcement + planning optimization.",
 "Agents executing consequential actions under IPI.",
 "n/a in snippet.",
 "Quantifies the defense-induced utility cost — the same axis as our defence-induced FN corruption finding.",
 "Medium: cite for the cost-of-guarantees argument.",
 SNIP,"https://arxiv.org/abs/2602.11416"],
# --- Sanitizers / detectors ---
["PI-26","sanitizer-detection-removal","2502.16580","Can Indirect Prompt Injection Attacks Be Detected and Removed?","Chen, Li, Sui, He, Liu, Song, Hooi","2025","2025-02-23",
 "Feasibility study of detecting AND removing IPI; benchmark dataset; segmentation-removal vs extraction-removal post-processing after detection.",
 "Trained detection models + two removal methods (segment; train extraction model).",
 "LLMs and open-source detection models on their crafted benchmark.",
 "n/a (feasibility framing; no single headline number in abstract).",
 "Detect-then-remove is exactly our D1-strip family upgraded with a detector; direct baseline for our advisory-stripping defense comparisons.",
 "Medium-high: removal-after-detection on documents is close to advisory stripping; our measured verdict-recovery + corruption-persistence angle is the differentiator.",
 FULL,"https://arxiv.org/abs/2502.16580"],
["PI-27","sanitizer-detection","2505.06311","Defending against Indirect Prompt Injection by Instruction Detection","Wen, Wang, Yang, Tang, Xie, Lyu, Dou, Wu","2025","2025-05-08",
 "Detects hidden instructions inside retrieved content (RAG) before use.",
 "Instruction-detection over retrieved content.",
 "RAG-integrated LLMs.",
 "n/a in snippet.",
 "Detector-on-retrieved-content baseline; same input shape as our advisory text.",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2505.06311"],
["PI-28","sanitizer","2510.08829","CommandSans: Securing AI Agents with Surgical Precision Prompt Sanitization","Das, Beurer-Kellner, Fischer, Baader","2025","2025-10-09",
 "Surgical, context-dependent prompt sanitization: removes only the unsafe parts instead of blanket filtering, since context-dependence makes defenses ill-calibrated.",
 "Precise sanitization of unsafe context fragments.",
 "LLM agents with many tools/sensitive data.",
 "n/a in snippet.",
 "Surgical sanitization is the principled version of our D1 (blanket strip); expect reviewers to ask why D1 is not CommandSans.",
 "Medium-high for defense comparisons.",
 SNIP,"https://arxiv.org/abs/2510.08829"],
["PI-29","sanitizer","2510.19207","Defending Against Prompt Injection with DataFilter","Wang, Chen, Alkhudair, Alomair, Wagner","2025","2025-10-22",
 "Filters untrusted data before the LLM accesses it (Wagner-group line after StruQ).",
 "Data filtering stage.",
 "LLM agents on untrusted external data.",
 "n/a in snippet.",
 "Same Wagner-group defense lineage as StruQ; part of the sanitize/filter baseline family.",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2510.19207"],
["PI-30","detection-internal-signal","2411.00348","Attention Tracker: Detecting Prompt Injection Attacks in LLMs","Hung, Ko, Rawat, Chung, Hsu, Chen","2024","2024-11-01",
 "Training-free detection via the 'distraction effect': important attention heads shift focus from original instruction to injected instruction.",
 "Tracks attention patterns on the instruction; no extra inference.",
 "Diverse models/datasets/attack types incl. small LLMs.",
 "AUROC improvement up to 10.0% over existing methods; works on small LLMs.",
 "Internal-signal detection is a candidate component for our corruption-detector direction; validated on small models, which matches our 2-3B scope.",
 "Medium-high: attention-signal evidence could complement or replace CodeBERT-fallback signals (P1 thread).",
 FULL,"https://arxiv.org/abs/2411.00348"],
["PI-31","detection-localization","2510.12252","PromptLocate: Localizing Prompt Injection Attacks","Jia, Liu, Shao, Jia, Gong","2025","2025-10-14",
 "Localizes the injected prompt (instructions vs data) inside contaminated input rather than only flagging presence.",
 "Localization of injected prompt span.",
 "Contaminated LLM inputs.",
 "n/a in snippet.",
 "Span-localization is exactly what a surgical D1 successor needs — closest detector work to a 'find and strip the corrupted span' defense.",
 "Medium-high for our strip-recovery story.",
 SNIP,"https://arxiv.org/abs/2510.12252"],
["PI-32","detection-deployable","2501.15145","PromptShield: Deployable Detection for Prompt Injection Attacks","Jacob, Alzahrani, Hu, Alomair, Wagner","2025","2025-01-25",
 "Deployable PI detector addressing operational constraints (incl. false-positive control) of prior detectors.",
 "Detector design for deployment.",
 "LLM-integrated applications.",
 "n/a in snippet.",
 "FP-control framing aligns with our FP verdict-drift concern.",
 "Low-medium.",
 SNIP,"https://arxiv.org/abs/2501.15145"],
["PI-33","defense-finetuning","2410.05451","SecAlign: Defending Against Prompt Injection with Preference Optimization","Chen, Zharmagambetov, Mahloujifar, Chaudhuri, Wagner, Guo","2024","2024-10-07",
 "Trains the model, via preference optimization, to prefer fulfilling the original instruction over any injected one.",
 "Preference-optimization fine-tuning (labeled CCS 2025 by the 2507.07417 abstract).",
 "LLM-integrated applications using external data.",
 "n/a in snippet (see 2507.07417: broken whitebox at 85-95%).",
 "Strongest fine-tuning defense of the family; its whitebox breakage bounds how far alignment-only defenses carry.",
 "Medium: baseline candidate; our no-retraining positioning stays distinct.",
 SNIP,"https://arxiv.org/abs/2410.05451"],
["PI-34","defense-finetuning","2507.07974","Defending Against Prompt Injection With a Few DefensiveTokens","Chen, Wang, Carlini, Sitawarin, Wagner","2025","2025-07-10",
 "Fine-tunes with a few defensive tokens to resist instruction override from data.",
 "Lightweight fine-tuning with defensive tokens.",
 "LLM systems on external data.",
 "n/a in snippet.",
 "Cheaper fine-tuning defense; candidate baseline if we ever run a tuned comparison on 2-3B.",
 "Low-medium.",
 SNIP,"https://arxiv.org/abs/2507.07974"],
# --- Adaptive attacks & defense evaluation ---
["PI-35","adaptive-attack","2503.00061","Adaptive Attacks Break Defenses Against Indirect Prompt Injection Attacks on LLM Agents","Zhan, Fang, Panchal, Kang","2025","2025-02-27",
 "Evaluates 8 IPI defenses under adaptive attacks and bypasses ALL of them.",
 "Adaptive attacker aware of the defense; consistent evaluation protocol.",
 "8 different IPI defenses on LLM agents.",
 "ASR > 50% against every one of the 8 defenses.",
 "The single most load-bearing prior for our NEG-39 adaptive-robustness question: any defense claim (D1, P3, A5) must face an adaptive attacker or be dismissed.",
 "Sets the required evaluation standard; our contribution can be the adaptive-eval protocol FOR the vuln-analysis verdict channel, which nobody has done.",
 FULL,"https://arxiv.org/abs/2503.00061"],
["PI-36","adaptive-attack-whitebox","2507.07417","May I have your Attention? Breaking Fine-Tuning based Prompt Injection Defenses using Architecture-Aware Attacks","Pandya, Labunets, Gao, Fernandes","2025","2025-07-10",
 "Novel attention-based optimization attack breaks whitebox fine-tuning defenses: StruQ, SecAlign, SecAlign++.",
 "Whitebox optimization attacks, architecture-aware (attention-based), modest attacker-budget increase.",
 "SecAlign (CCS 2025), SecAlign++, StruQ (USENIX Security 2025).",
 "Attack success 85-95% on unseen prompts.",
 "Directly demotes the trusted-data-separation fine-tuning family in our threat model: even 'trained separation' is not a safe assumption for adversarial-context claims.",
 "Strengthens our story that non-alignment mechanisms (provenance + verification + abstention) are needed; cite prominently.",
 FULL,"https://arxiv.org/abs/2507.07417"],
["PI-37","defense-evaluation","2505.18333","A Critical Evaluation of Defenses against Prompt Injection Attacks","Jia, Shao, Liu, Jia, Song, Gong","2025","2025-05-23",
 "Principled two-axis defense evaluation: (1) effectiveness vs existing AND adaptive attacks with diverse target/injected prompts, (2) general-purpose utility preservation.",
 "Systematic re-evaluation framework (PIEval).",
 "Existing PI defenses (re-evaluated).",
 "Existing defenses are not as successful as previously reported under the principled methodology.",
 "This is the evaluation charter our defense experiments should follow — and our defence-induced FN/clean-utility-cost measurements already implement axis (2).",
 "Our eval-protocol contribution can be framed as extending this methodology to the verdict-corruption (non-exfiltration) setting — currently uncovered.",
 FULL,"https://arxiv.org/abs/2505.18333"],
["PI-38","adaptive-attack-detection","2507.05630","How Not to Detect Prompt Injections with an LLM","Choudhary, Anshumaan, Palumbo, Jha","2025","2025-07-08",
 "Breaks known-answer-detection (KAD) defenses with adaptive attacks despite previously reported high performance.",
 "Adaptive attacks against LLM-based known-answer detectors.",
 "KAD-scheme defenses.",
 "n/a in snippet (defense broken; specifics beyond snippet not read).",
 "Any detector-augmented defense in our pipeline must anticipate KAD-style adaptive evasion.",
 "Supports pairing our corruption signal with a code-grounded (non-LLM-only) verification channel.",
 SNIP,"https://arxiv.org/abs/2507.05630"],
["PI-39","adaptive-attack-RL","2603.13026","PISmith: Reinforcement Learning-based Red Teaming for Prompt Injection Defenses","Yin, Geng, Wang, Jia","2026","2026-03-13",
 "RL-trained red-teamer generating adaptive attacks against PI defenses; finds robustness against adaptive attacks insufficiently evaluated.",
 "RL-based attack generation harness.",
 "Many proposed PI defenses.",
 "n/a in snippet.",
 "Turnkey adaptive-attack generator we could reuse for the NEG-39 red-team round instead of hand-crafting.",
 "Medium-high: methodological tool for our adaptive round.",
 SNIP,"https://arxiv.org/abs/2603.13026"],
["PI-40","adaptive-attack-RL","2602.05746","Learning to Inject: Automated Prompt Injection via Reinforcement Learning","Chen, Zhang, Tramer","2026","2026-02-05",
 "RL-trained automated injection that outperforms adapted jailbreak optimizers; closes the human-red-teamer gap.",
 "RL attack optimization specialized to injection (vs generic compliance jailbreaks).",
 "LLM agents.",
 "n/a in snippet.",
 "Frontier adaptive attacker class for future rounds.",
 "Medium.",
 SNIP,"https://arxiv.org/abs/2602.05746"],
["PI-41","benchmark-long-context","2608.28411","LongPIBench: A Long-Context Benchmark for Prompt Injection","Liu, Jia, Gong, Jia","2026","2026-08-28",
 "First dedicated benchmark for PI attacks/defenses in LONG-context settings, where existing short-context benchmarks do not transfer.",
 "Long-context attack/defense benchmark suite.",
 "LLMs in long-context applications.",
 "n/a in snippet.",
 "Our code+advisory contexts are long; this benchmark family is the honest eval setting our corruption experiments should reference or join.",
 "Medium-high: long-context corruption dynamics may differ — an open empirical question adjacent to our C2/C3 results.",
 SNIP,"https://arxiv.org/abs/2608.28411"],
["PI-42","survey","2601.22240","A Systematic Literature Review on LLM Defenses Against Prompt Injection and Jailbreaking: Expanding NIST Taxonomy","Correia et al.","2026","2026-01-29",
 "Systematic literature review of LLM defenses against PI and jailbreaking, expanding the NIST AI-risk taxonomy.",
 "SLR methodology over defense literature.",
 "LLM defense literature.",
 "n/a in snippet.",
 "Use for taxonomy alignment and completeness checks of our related-work section.",
 "Map-only.",
 SNIP,"https://arxiv.org/abs/2601.22240"],
]

with open(path, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    if not exists:
        w.writerow(header)
    w.writerows(rows)

print("rows written:", len(rows))
print("header:", header)
