#!/usr/bin/env python
"""Artifact integrity manifest for the RefuseGuard repro package (S-R4).

Writes SHA256 checksums of the SMALL numeric artifacts the paper's numbers are
read from into outputs/master/ARTIFACT_MANIFEST.sha256 (sha256sum -c format).
Large git-ignored payloads (raw jsonl, llm_cache, checkpoints) are deliberately
NOT covered — the manifest guarantees the integrity of the released results
bundle, not a fresh clone (see README "Artifact integrity").

Covered (all < ~1 MB each): master aggregate, E0 gate verdict + per-model
results, E2E3 per-model results, E5/E6/E7 results, E8 recomputed summaries,
transformer eval + fallback threshold, calibration reports, benchmark metadata.

Usage:
    .venv/bin/python scripts/make_manifest.py            # (re)write manifest
    .venv/bin/python scripts/make_manifest.py --check    # verify only (exit 0/1)

Shell equivalent (any files you have):
    sha256sum -c outputs/master/ARTIFACT_MANIFEST.sha256     # Linux
    shasum -a 256 -c outputs/master/ARTIFACT_MANIFEST.sha256 # macOS
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "outputs" / "master" / "ARTIFACT_MANIFEST.sha256"

# Small, load-bearing numeric artifacts (relative to repo root).
FILES: list[str] = [
    # master aggregate (single source of truth for the paper's numbers)
    "outputs/master/master_results.json",
    "outputs/master/round7_master.json",
    "outputs/master/round7_token_map.json",
    "outputs/master/round6_bias.json",
    "outputs/experiments/round7_rq8/metrics_round7_rq8.json",
    "outputs/experiments/round7_rq8/results_llama3b.json",
    "outputs/experiments/round7_rq8/results_granite2b.json",
    "outputs/experiments/round7_7b/results_qwen7b__vul__A0.json",
    "outputs/experiments/round7_7b/results_qwen7b__vul__A5.json",
    "outputs/experiments/round7_7b/results_qwen7b__vul__A1.json",
    "outputs/experiments/round7_7b/results_qwen7b__benign__B0.json",
    "outputs/experiments/round7_7b/smoke_7b.json",
    "outputs/master/master_results.md",
    # E0 reproduction gate
    "outputs/experiments/round3_e0/gate_verdict.json",
    "outputs/experiments/round3_e0/summary.json",
    "outputs/experiments/round3_e0/qwen3b/results.json",
    "outputs/experiments/round3_e0/llama3b/results.json",
    "outputs/experiments/round3_e0/granite2b/results.json",
    # E2/E3 robustness (3 models) + E4 breakdown
    "outputs/experiments/round3_e2e3/qwen3b/results.json",
    "outputs/experiments/round3_e2e3/llama3b/results.json",
    "outputs/experiments/round3_e2e3/granite2b/results.json",
    # E5/E6/E7
    "outputs/experiments/round3_e5/results.json",
    "outputs/experiments/round3_e6/results.json",
    "outputs/experiments/round3_e7/e7_fusion_results.json",
    # E8 recomputed summaries (mandatory corrected source for E8-Llama)
    "outputs/experiments/round3_e8/recomputed/recompute_e8_monitor.json",
    "outputs/experiments/round3_e8_llama3b/recomputed/recompute_e8_monitor.json",
    # transformer baseline (B4)
    "outputs/transformer/final_eval.json",
    "outputs/transformer/codebert_eval_vd_s_metrics.json",
    "outputs/transformer/fallback_threshold.json",
    "outputs/transformer/calibration/Qwen_Qwen2.5-Coder-3B-Instruct/full_report.json",
    "outputs/transformer/calibration/unsloth_Llama-3.2-3B-Instruct/full_report.json",
    # benchmark metadata (small; contents of data/ stay git-ignored)
    "data/benchmarks/bench_v1/bench_v1_meta.json",
    "data/benchmarks/e0_prompts_v1_meta.json",
    "data/benchmarks/safety_contrast_v1.json",
    # round-11 P0: corrected-baseline grid + trivial baseline + paper macros
    "outputs/packguard/p0/p0_results.json",
    "outputs/packguard/trivial/trivial_results.json",
    "paper2/p0_macros/numbers.tex",
]

HEADER = (
    "# RefuseGuard artifact manifest (SHA256), generated by scripts/make_manifest.py.\n"
    "# Covers the small numeric artifacts the paper's numbers are read from.\n"
    "# Verify:  sha256sum -c outputs/master/ARTIFACT_MANIFEST.sha256   (Linux)\n"
    "#          shasum -a 256 -c outputs/master/ARTIFACT_MANIFEST.sha256 (macOS)\n"
    "# After re-running any pipeline stage, regenerate with:\n"
    "#   .venv/bin/python scripts/make_manifest.py\n"
    "# Limitation: outputs/ and data/ contents are git-ignored; this manifest\n"
    "# ships with the released OUTPUTS BUNDLE (integrity of the bundle), so on a\n"
    "# fresh clone the checks pass only after downloading/re-running the pipeline.\n"
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def write() -> int:
    lines, missing = [], []
    for rel in FILES:
        p = ROOT / rel
        if not p.is_file():
            missing.append(rel)
            continue
        lines.append(f"{sha256(p)}  {rel}")
    if missing:
        print(f"[manifest] WARNING — {len(missing)} listed files missing "
              f"(manifest written WITHOUT them):", file=sys.stderr)
        for m in missing:
            print(f"  missing: {m}", file=sys.stderr)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"[manifest] wrote {MANIFEST.relative_to(ROOT)} "
          f"({len(lines)} files, {len(missing)} missing)")
    return 1 if missing else 0


def check() -> int:
    if not MANIFEST.is_file():
        print(f"[manifest] FAIL — {MANIFEST.relative_to(ROOT)} not found; "
              "run scripts/make_manifest.py first", file=sys.stderr)
        return 1
    ok = bad = missing = 0
    for raw in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        digest, rel = line.split(None, 1)
        p = ROOT / rel.strip()
        if not p.is_file():
            print(f"  MISSING: {rel}")
            missing += 1
            continue
        if sha256(p) == digest:
            ok += 1
        else:
            print(f"  MISMATCH: {rel}")
            bad += 1
    print(f"[manifest] {ok} ok, {bad} mismatched, {missing} missing "
          f"(of {ok + bad + missing} listed)")
    return 0 if (bad == 0 and missing == 0) else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify existing manifest instead of (re)writing")
    args = ap.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
